#Spring configuration
spring:
  #Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/better
    username: postgres
    password: postgres
  #JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  #Spring Batch
  batch:
    initialize-schema: always
#Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
      #level:
    #org.springframework: info
    #org.hibernate: debug
#Server configuration
server:
  port: 8080
  servlet:
    context-path: /
file:
  dir:
    input: src/main/resources/nfs/input/
    out: src/main/resources/nfs/out/
    error: src/main/resources/nfs/error/
    temp: src/main/resources/nfs/temp/
  path:
    schema:
      xsd: src/main/resources/schema/doctor.xsd
      json: src/main/resources/schema/json-schema.json
      schema-lang: http://www.w3.org/2001/XMLSchema

