#Spring configuration
spring:
  #Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/better
    username: postgres
    password: postgres
#JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
#Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
      #level:
      #org.springframework: info
    #org.hibernate: debug
server:
  port: 8080
#Server configuration