package si.better.ddp.model.report;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.web.context.annotation.RequestScope;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDateTime;

/**
 * @author ahmetspahics
 */
@Entity
@Table(name = "DOCUMENT_REPORT")
@Data
@NoArgsConstructor
@AllArgsConstructor
@RequestScope
public class DocumentReport
{
    /**
     * id - autogenerated value
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", updatable = false, nullable = false)
    @Setter(AccessLevel.NONE)
    private long id;

    /**
     * doctorId - obtained from input resource
     */
    @Column(name = "DOCTOR_ID")
    private String doctorId;

    /**
     * error -  error message
     */
    @Column(name = "ERROR", length = 1024)
    private String error;

    /**
     * executionTime - execution start time
     */
    @Column(name = "EXECUTION_TIME", nullable = false)
    private LocalDateTime executionTime;

    /**
     * stepComponent - represents Spring Batch Step level
     */
    @Column(name = "SOURCE", nullable = false)
    @Enumerated(EnumType.STRING)
    private Source source;

    public DocumentReport(LocalDateTime executionTime, Source source)
    {
        this.executionTime = executionTime;
        this.source = source;
    }
}
